pressbooks/pressbooks-book

- functions.php
Depends on: https://github.com/pressbooks/pressbooks/pull/867
> Content licensing (Fixes #805)

- functions.php
Fixes most of:
https://github.com/pressbooks/pressbooks/issues/805#issuecomment-319168962
> Fix: Freeform/custom copyright notice does not appear in footer

- assets/book/styles/components/pages/_back-matter.scss
- assets/book/styles/components/pages/_chapters.scss
- assets/book/styles/components/pages/_front-matter.scss
- assets/book/styles/variables/_pages.scss
- assets/legacy/styles/_epub-house-style.scss
- assets/legacy/styles/_pdf-house-style.scss
See https://github.com/pressbooks/pressbooks/issues/805.
> Add basic styles for section license

- functions.php
Add $deps, a cache busting version number, fix deprecated functions.
> Custom Styles Cleanup

- functions.php
- single.php
> Use McLuhan as default stylesheet for Custom CSS

- partials/content-single-legacy.php
- partials/content-single.php
- single.php
This wasn't updated for the new Contributors class.
> Display authors properly on single view

- functions.php
- partials/content-cover-book-info.php
- partials/content-cover-metadata.php
@see https://codex.wordpress.org/Function_Reference/_n
@see https://codex.wordpress.org/Function_Reference/_n_noop
> Singular/plural contributor strings. (fixes #149)

- header.php
- inc/helpers/namespace.php
- index.php
- partials/content-cover-book-header.php
- partials/content-cover-toc.php
Depends on:
https://github.com/pressbooks/pressbooks/pull/1163
> Hide read buttons (fix #144)

- partials/content-single-legacy.php
- partials/content-single.php
Fixes a bug where part titles were not displayed in the webbook.
> Display part titles

- partials/content-cover-book-header.php
Props @colomet for the report.
> Use properly-sized cover image (fix #250)

- inc/helpers/namespace.php
- tests/test-helpers.php
Required for https://github.com/pressbooks/pressbooks/pull/1392.
> Add support for CC0 license (fixes pressbooks/pressbooks#1331)

- assets/book/styles/variables/_elements.scss
- assets/styles/components/_elements.scss
> Fix header type scaling

- assets/styles/components/_colors.scss
- assets/styles/components/_elements.scss
- packages/buckram/assets/styles/components/_colors.scss
- packages/buckram/assets/styles/components/elements/_links.scss
- packages/buckram/assets/styles/variables/_colors.scss
- packages/buckram/assets/styles/variables/_elements.scss
Also fixes pressbooks/pressbooks#1306.
> Add link differention for print/digital (fix #317)

- inc/helpers/namespace.php
- partials/content-toc.php
- tests/test-helpers.php
Corresponding PR for https://github.com/pressbooks/pressbooks/pull/1453.
> Move subsection caching to core (fix pressbooks/pressbooks#1438)

- packages/buckram/assets/styles/components/section-titles/_parts.scss
- packages/buckram/assets/styles/variables/_section-titles.scss
> Add support for maps on part title align (fix #364)

- packages/buckram/assets/styles/components/media/_images.scss
- packages/buckram/assets/styles/variables/_media.scss
> Add image caption text indent

- packages/buckram/assets/styles/components/elements/_tables.scss
- packages/buckram/assets/styles/variables/_elements.scss
Added variables that allow left borders on full tables and right borders on full tables.
> Add left and right table border variables

- packages/buckram/assets/styles/components/toc/_generic.scss
- packages/buckram/assets/styles/components/toc/_left.scss
TOC section license properly goes to next line.
> Toc section license

- inc/helpers/namespace.php
- packages/buckram/assets/styles/components/media/_interactive-content.scss
- packages/buckram/assets/styles/variables/_media.scss
- tests/bootstrap.php
- tests/test-helpers.php
> Fix text indent on media fallback images

- inc/helpers/namespace.php
- partials/content-cover-book-header.php
- tests/test-helpers.php
Depends on https://github.com/pressbooks/pressbooks/pull/1589.
> Move get_name_for_filetype() to core

- functions.php
- inc/actions/namespace.php
- tests/test-actions.php
Depends on https://github.com/pressbooks/pressbooks/pull/1594.
> Add JSON-LD metadata to webbook (resolves #434)

- inc/actions/namespace.php
We don't need these at present, so we can remove them.
> Remove Gutenberg block styles

- functions.php
- header.php
- inc/actions/namespace.php
Depends on https://github.com/pressbooks/pressbooks/pull/1595.
> Add citation metadata, cleanup deprecated metadata (fix #435)

- footer.php
https://github.com/pressbooks/ideas/issues/180
Pressbooks and Aldine have been changed, footer in this repo was overlooked
> Add contact link form and checks for contact link display

- partials/content-cover-toc.php
Added missing domain to a couple of translations.
This should fix issue #569 and would only require updating the .pot and other translation files.
> Updated content-cover-toc partial

- packages/buckram/CHANGELOG.md
- packages/buckram/assets/styles/components/toc/_left.scss
fix #556, fix #557 
Also related: pressbooks/pressbooks-clarke#45
> TOC overflow issue on triple digits and larger font sizes

- packages/buckram/CHANGELOG.md
- packages/buckram/assets/styles/components/elements/_tables.scss
> Full grid classes added

- partials/content-toc.php
> Fix validation error: ' in an unquoted attribute value

- assets/book/typography/styles/_shapeshifter-font-stack-epub.scss
- assets/book/typography/styles/_shapeshifter-font-stack-prince.scss
- assets/book/typography/styles/_shapeshifter-font-stack-web.scss
Depends on: https://github.com/pressbooks/pressbooks/pull/1792
> Shapeshifter: Choose your own font feature

- footer.php
Fixes: https://github.com/pressbooks/pressbooks-aldine/issues/191
> Fix: Contact link customization

- inc/actions/namespace.php
- tests/test-actions.php
> Suppress media attachments for bots

- .travis.yml
This PR updates the github API personal token in file .travis.yml by env. var $GITHUB_ACCESS_TOKEN
> PB-88 - Update github token

- assets/src/scripts/routes/common.js
- partials/content-cover-book-header.php
This PR attempts to address the concerns outlined in [this](https://github.com/pressbooks/pressbooks/issues/1790) discussion.
The acceptance criteria (per the discussion linked above) is as follows:
1. The menu should close when the user tabs out of the menu
2. Pressing the `esc` key should close the menu
I also addressed a couple of extra issues while I was in there:
1. The menu should close when the user clicks anywhere outside of the menu
2. When an item in the list is active and the user presses `enter`, a download dialogue should be triggered
I attempted to stay with the patterns that were already present in the documents edited in this PR.  Before submitting this PR, I also ran the linter and corrected any stylistic things it complained about.
As always, I am more than happy to get …
> 1790 - "Download This Book" Select is inaccessible

- packages/buckram/assets/styles/components/specials/_footnotes.scss
Reverts footnote margin-left change
> Revert footnote margin-left change

- .travis.yml
- README.md
- composer.json
- composer.lock
- inc/actions/namespace.php
- style.css
Declare composer version, update required PHP, WordPress, PB versions & remove PHP 7.1 & 7.2 from test matrix.
> Declare composer version, update required PHP, WordPress, PB

- packages/aetna/package-lock.json
- packages/aetna/package.json
- packages/buckram/CHANGELOG.md
- packages/buckram/assets/styles/buckram.scss
- packages/buckram/package-lock.json
- packages/buckram/package.json
This PR bumps the version of Buckram and Aetna used by Pressbooks-book
> Pb book rc v2 11 2

- partials/content-single.php
This PR is part of https://github.com/pressbooks/pressbooks/pull/2348
> Pluralization fix

- packages/buckram/assets/styles/components/specials/_contributors.scss
- packages/buckram/assets/styles/variables/_specials.scss
Fixes for #866. Accompanies https://github.com/pressbooks/pressbooks/pull/2393
> Contributor style fixes

- packages/buckram/CHANGELOG.md
- packages/buckram/assets/styles/buckram.scss
- packages/buckram/package-lock.json
- packages/buckram/package.json
Release candidate for Buckram 1.6.0
> chore(release): buckram@1.6.0

- header.php
- partials/content-cover-toc.php
This PR makes the new nav labels we've added available for translators.
> Makes new nav labels translatable

- packages/buckram/CHANGELOG.md
- packages/buckram/assets/styles/buckram.scss
- packages/buckram/package-lock.json
- packages/buckram/package.json
Release candidate for Buckram 1.7.0
> chore(release): buckram@1.7.0

- .github/workflows/update-translations.yml
remove unnecessary lines from automated translation workflow
> ci: remove unnecessary lines

- assets/book/typography/styles/_CardoFont.scss
- assets/src/styles/components/_toc.scss
- assets/styles/components/_elements.scss
- assets/styles/components/_media.scss
- assets/styles/components/_pages.scss
- assets/styles/components/_section-titles.scss
- assets/styles/components/_specials.scss
- packages/aetna/assets/styles/common/_functions.scss
- packages/aetna/assets/styles/common/_variables.scss
- packages/aetna/assets/styles/layouts/_footer.scss
- packages/aetna/assets/styles/layouts/_header.scss
- packages/buckram/assets/styles/components/specials/_textboxes.scss
Reverts pressbooks/pressbooks-book#916
> Revert "fix: use math.div instead of `/`"

- inc/helpers/namespace.php
This PR adds support to show custom licenses. Partial fix for https://github.com/pressbooks/private/issues/661, linked to https://github.com/pressbooks/pressbooks/pull/2559 and https://github.com/pressbooks/pressbooks-plugins-config/pull/15
> feat: support for custom license

- .github/workflows/.pipeline.yml
- composer.json
Partial fix for https://github.com/pressbooks/private/issues/801
> Add PHP 8.0 to text matrix

- inc/helpers/namespace.php
Issue pressbooks/private#782. Accompanies pressbooks/pressbooks#2638 and pressbooks/pressbooks-aldine#316
This PR adds support to the structural changes in the institutions field (see pressbooks/pressbooks#2638).
1. Add one or more institutions to the book in the Book Info option
1. Go to the book homepage and check if the information is displayed properly (when the book has no institutions, this won't be shown in the homepage)
> feat: support institutions changes

- .github/workflows/update-pot.yml
- .github/workflows/update-translations.yml
Partial fix for https://github.com/pressbooks/private/issues/717
> Automatically update translations

- style.css
Sync master commit message to dev
> Update version to next minor dev

- partials/content-cover-metadata.php
- single.php
Partial fix for https://github.com/pressbooks/pressbooks/issues/2429. Accompanies https://github.com/pressbooks/pressbooks/pull/2728
> Replace DOI resolver URL

- header.php
Update CTA message: "Want to create or adapt books like this? Learn more about how Pressbooks supports open publishing practices."
> Update CTA mesage

- inc/helpers/namespace.php
Issue #1114 
This PR aims to fix the H5P listing not showing the H5P with id 1.
**How to test**
Follow steps mentioned in the ticket, all H5P activities should be properly listed.
> fix: H5P listing offset

- .github/workflows/standards-and-tests.yml
- composer.json
- composer.lock
Part of pressbooks/private#961
This PR updates the code to support php 8
> chore: php 8 support
