pressbooks/pressbooks-book

assets/book/styles/components/_elements.scss, assets/book/styles/components/_media.scss, assets/book/styles/components/_pages.scss, assets/book/styles/components/_section-titles.scss, assets/book/styles/components/_specials.scss, assets/book/styles/components/_structure.scss
This PR consolidates import of component partials (e.g. `assets/book/styles/components/elements/_*.scss`) into a single `_component-name.scss` partial within the `assets/book/styles/components/` directory. This lets theme developers import all component partials with a single `@import` rule. So, for example:
```
@import 'components/elements/blockquotes';
@import 'components/elements/body';
@import 'components/elements/headings';
@import 'components/elements/links';
@import 'components/elements/lists';
@import 'components/elements/miscellaneous';
@import 'components/elements/paragraphs';
@import 'components/elements/tables';
```
Becomes:
```
@import 'components/elements';
```
=> Add meta-component partials for easier theme development

assets/book/styles/components/structure/_numbering.scss
The `.introduction` class is added to the first item in the book, which is sometimes front matter, sometimes parts, and sometimes chapters. The counter reset was not properly applying to parts. This PR should fix it.
=> Fix issue where introduction counter is not reset

assets/book/styles/buckram.scss, assets/book/styles/components/structure/_content-strings.scss, assets/legacy/styles/_pdf-house-style.scss, package-lock.json, package.json, yarn.lock
Fixes an issue where book authors were not appearing in running content.
=> Update Buckram to 0.7.1, fix author string for legacy themes

inc/helpers/namespace.php, single.php
Depends on https://github.com/pressbooks/pressbooks/pull/1165
Related to
https://github.com/pressbooks/pressbooks-book/issues/151
=> Use $post_id instead of $slug when calling pb_get_chapter_number()

inc/actions/namespace.php, inc/helpers/namespace.php, partials/content-toc.php
When using redis (or memcached) transients are not in the database so querying for them in the DB was returning nothing.
The fix is to delete every combination of the transient for good measure.
=> Fix TOC caching

inc/helpers/namespace.php
Before:
After:
(For front matter/back matter with the 'Miscellaneous' type assigned, they will be labelled 'Front Matter' or 'Back Matter'.)
=> Add front/back matter types to navigation (fixes pressbooks/pressbooks#1311)

inc/helpers/namespace.php, partials/content-cover-book-info.php, tests/test-helpers.php
This is displayed if a source book has been deleted:
=> Support deleted source books in cloned book info (fix #254)

packages/buckram/assets/styles/components/section-titles/_chapters.scss
This pull request makes sure the chapter number before content does not display if the chapter is set to numberless.
=> Numberless chapter targets before content

packages/buckram/assets/styles/components/pages/_front-matter.scss
This fixes an issue with a bunch of Buckram themes. We already allow the `page-break-before` property to respond to the recto-verso settings for PDF. This rule was adding a blank page before the copyright page in EPUB exports, which it should not.
=> Remove unexpected blank page before copyright page (EPUB)

inc/helpers/namespace.php, tests/bootstrap.php, tests/test-helpers.php
Unless chapter is licensed differently, it should display the book license statement
Depends on https://github.com/pressbooks/pressbooks/pull/1561
=> Chapter licenses fix

packages/buckram/assets/styles/components/_colors.scss, packages/buckram/assets/styles/components/specials/_textboxes.scss, packages/buckram/assets/styles/variables/_colors.scss, packages/buckram/assets/styles/variables/_specials.scss
At some point we somehow ended up with two separate colour variables both of which are supposed to do the same thing— provide the background colour for shaded textboxes. This PR unifies them.
=> Fall back to shaded variable for textbox colours

packages/buckram/assets/styles/components/media/_interactive-content.scss
This PR ensures that interactive content fallback images are always centred, regardless of page size.
=> Center interactivate content fallback images

packages/buckram/CHANGELOG.md, packages/buckram/assets/styles/components/section-titles/_back-matter.scss, packages/buckram/assets/styles/components/section-titles/_chapters.scss, packages/buckram/assets/styles/components/section-titles/_front-matter.scss, packages/buckram/assets/styles/components/section-titles/_generic.scss, packages/buckram/assets/styles/variables/_section-titles.scss
This prevents text-indent rules applied to paragraphs from indenting section authors.
=> Add $section-author-text-indent variable

packages/buckram/CHANGELOG.md, packages/buckram/assets/styles/components/pages/_titles.scss, packages/buckram/assets/styles/variables/_pages.scss
Add variable for publisher and publisher city float and set variable to none.
=> Publisher float

packages/buckram/CHANGELOG.md, packages/buckram/assets/styles/components/structure/_blank.scss
Remove running content from post-introduction front matter blank pages
=> Post intro blank pages

packages/buckram/assets/styles/components/elements/_lists.scss
=> Add 'if-map-get' to dt-color variable to fix parse error (fix: #527)

packages/buckram/CHANGELOG.md, packages/buckram/assets/styles/variables/_specials.scss
An update to this PR: https://github.com/pressbooks/pressbooks-book/pull/544
=> Change footnote font size in prince from `em` to `rem`

packages/buckram/CHANGELOG.md, packages/buckram/assets/styles/components/specials/_footnotes.scss, packages/buckram/assets/styles/variables/_colors.scss, packages/buckram/assets/styles/variables/_specials.scss
Related: https://github.com/pressbooks/pressbooks-book/pull/546 https://github.com/pressbooks/pressbooks-book/pull/544
=> Add extra footnote variables to prevent inheriting parent styles

packages/buckram/CHANGELOG.md, packages/buckram/assets/styles/components/toc/_generic.scss
fix #558
Add missing 'a' to make sure color is targeting the TOC part title.
=> Target toc-part-title-color variable for print

packages/buckram/assets/styles/components/specials/_pullquotes.scss
Fixes https://github.com/pressbooks/pressbooks-book/issues/337
=> Change default pullquote styling to 'inline-block' for PDF exports

packages/buckram/assets/styles/components/specials/_footnotes.scss
Removes extra SCSS rules (.clear already exists and can be used to achieve desired effect).
=> Remove extra SCSS

assets/book/typography/styles/_NotoSansArmenianFont.scss, assets/book/typography/styles/_NotoSansDevanagariFont.scss, assets/book/typography/styles/_NotoSerifArmenianFont.scss, assets/book/typography/styles/_fonts-hy.scss, packages/buckram/assets/styles/components/specials/_textboxes.scss, partials/content-cover-book-info.php
Add support for Armenian language scripts. Along with https://github.com/pressbooks/pressbooks/pull/1946, provides fix for https://github.com/pressbooks/ideas/issues/313
Fix for https://github.com/pressbooks/pressbooks-book/issues/695 by ensuring that heading elements inside of textbox__header elements receive expected color value.
Fix for https://github.com/pressbooks/pressbooks-book/issues/694 by moving extra 'by' statement before publisher name inside of conditional check for book clone attribution.
=> Add support for Armenian language scripts, fix textbox heading color & clone attribution bugs

.github/workflows/.pipeline.yml, packages/buckram/assets/styles/components/media/_images.scss
This should fix #791 and #792 
This PR attempts to solve PDF and EPUB floating image positioning.
It also fixes a GitHub pipeline issue that @ho-man-chan mentioned.
* Create a book with floating (left, right) and centered images with no caption
* Check that the book renders properly as web pages
* Export a PDF and/or EPUB version of the book and check if the content is properly rendered
* Make sure that inline images keep rendering as inline
=> Fix positioning for images without caption in PDFs

.github/workflows/.pipeline.yml, package-lock.json, package.json, packages/aetna/package-lock.json, packages/aetna/package.json, packages/buckram/package-lock.json, packages/buckram/package.json
Adds Pressbooks Build Tools as a devDependency (see pressbooks/pressbooks#2235).
=> chore: add pressbooks-build-tools as devDependency

partials/content-single.php
Currently, the edit chapter button is placed outside of the content div when there are no authors assigned to a chapter:
This PR fixes this bug, which was accidentally introduced into the content-single page template during the hackathon. 
**To test:**
1. Apply this branch
2. Log into a book
3. Open a chapter that does not have an author assigned
4. View the placement of the edit chapter button at the bottom of the content block
5. Open a chapter that does have an author assigned in chapter metadata
6. View the placement of the edit chapter button at the bottom of the content block
Both cases should look like this:
=> Fix HTML structure bug in content-single

packages/buckram/assets/styles/components/media/_images.scss
Issue #850 
This PR removes image adjustments on PDFs for centered aligned images ([see](https://github.com/pressbooks/pressbooks-book/issues/850#issuecomment-910356523)).
1. Import an image, and insert as "large" into a chapter.
1. Set an alignment for center, left or right.
1. Export as a PDF
1. Left and right aligned images should have the sized adjusted. Centered images should remain untouched.
=> Adjust image size only for left and right aligned ones

.github/workflows/.pipeline.yml, page-buy.php
This PR replaces references to ibooks with applebooks on the buy book page. It accompanies https://github.com/pressbooks/pressbooks-book/pull/886.
It also includes minor tweaks to improve the CI pipeline.
To test:
1. Check out this branch and the `pb-2446-improve-publish` branch of Pressbooks 
2. Enter URL values for each of the available fields on a book's publish page
3. Visit the buy book link from the book's homepage
3. Check that the Apple books option displays as it did previously
=> Fix buy links

header.php, inc/helpers/namespace.php
Partial fix for https://github.com/pressbooks/pressbooks-book/issues/874. Accompanies https://github.com/pressbooks/pressbooks-aldine/pull/282
=> Add screen-reader only labels for nav elements

header.php, partials/content-cover-toc.php
Fix for https://github.com/pressbooks/pressbooks-book/issues/874. Previous PR (https://github.com/pressbooks/pressbooks-aldine/pull/282) applied the ToC label to top nav menu and didn't add labels to ToC nav on book homepage or reading interface.
To test:
1. Visit network homepage and check that top nav has primary navigation aria-label
2. Visit book homepage and make sure that top nav has 'primary navigation' screen reader text label and ToC nav has 'Book Contents Navigation' screen reader text label
3. Visit chapter inside a book and make sure top nav has 'primary navigation' screen reader text label, ToC nav has 'Book Contents Navigation' screen reader text label, and previous/next buttons have 'previous/next navigation screen reader text label'
=> Fix aria-labels for nav elements

.github/workflows/.pipeline.yml, assets/legacy/styles/_epub-house-style.scss, assets/legacy/styles/_mobi-house-style.scss, assets/legacy/styles/_pdf-house-style.scss, assets/legacy/styles/_prince-toc.scss, composer.lock, packages/buckram/assets/styles/components/_colors.scss, packages/buckram/assets/styles/components/pages/_titles.scss, packages/buckram/assets/styles/components/section-titles/_back-matter.scss, packages/buckram/assets/styles/components/section-titles/_chapters.scss, packages/buckram/assets/styles/components/section-titles/_front-matter.scss, packages/buckram/assets/styles/components/section-titles/_parts.scss, packages/buckram/assets/styles/components/toc/_generic.scss, packages/buckram/assets/styles/variables/_pages.scss, packages/buckram/tests/features/images/large-captioned/index.html
This PR closes https://github.com/pressbooks/pressbooks/issues/2452
How to test.
Export a book with different formats and you should see the same styling as the integrations/production networks.
=> fix: new semantic HTML selectors

assets/legacy/styles/_prince-toc.scss, packages/buckram/assets/styles/components/pages/_back-matter.scss, packages/buckram/assets/styles/components/pages/_chapters.scss, packages/buckram/assets/styles/components/pages/_front-matter.scss, packages/buckram/assets/styles/components/pages/_titles.scss, packages/buckram/assets/styles/components/section-titles/_back-matter.scss, packages/buckram/assets/styles/components/section-titles/_chapters.scss, packages/buckram/assets/styles/components/section-titles/_front-matter.scss, packages/buckram/assets/styles/components/toc/_generic.scss
Fixes pressbooks/pressbooks#2300 and pressbooks/pressbooks#2485. Accompanies pressbooks/pressbooks#2532.
This PR handles the styling portion for the digital PDF accessibility improvements.
See pressbooks/pressbooks#2485 for a clear understanding and make sure of the following:
- Half title page and title page are not visible in digital pdf bookmarks
- Table fo contents is a level 1 bookmark
- Each front/back matter is displayed as a level 1 bookmark
- If a book has more than 1 visible part, ensure that the title of each part is displayed as a level 1 bookmark
- Display the title of each chapter within a visible part as level 2 bookmark
- Display the title of each chapter within an invisible part as a level 1 bookmark
- If the two-level ToC enabled, all H1s inside of chapters within a …
=> feat: Improve digital PDF a11y

footer.php
Fix for https://github.com/pressbooks/ideas/issues/399
To test:
1. checkout this branch
2. navigate to the footer of a book or any chapter in a book
3. observe that a valid link to the Pressbooks Directory has been added
=> Add Directory link to footer

inc/helpers/namespace.php, page-h5p-listing.php, tests/test-helpers.php
Issue: https://github.com/pressbooks/pressbooks-lti-provider-1p3/issues/163
This change adds the option to filter by a specific h5p activity in the h5p activities listing page by passing the h5p_id get parameter. It also adds id attributes to the activities in order to be able to anchor to a specific activity id when needed.
This PR could be tested and merged independently from: https://github.com/pressbooks/pressbooks-lti-provider-1p3/pull/192
Add the h5p_id get parameter with some valid h5p activity id in the h5p listing page for a book. It must display 1 single activity.
=> feature: add get parameter for filter h5p activity in h5p listing page

inc/helpers/namespace.php, partials/content-cover-book-header.php, partials/content-cover-book-info.php, partials/content-cover-metadata.php, tests/test-helpers.php
Partial fix for pressbooks/pressbooks-aldine#305
This PR adds the [newly created](https://github.com/pressbooks/pressbooks/pull/2587) Institutions info to the book homepage.
1. Add one or more institutions to the book in the Book Info option
2. Go to the book homepage and check if the information is displayed properly (when the book has no institutions, this won't be shown in the homepage)
=> feature: Display institution information on book homepage

README.md, inc/helpers/namespace.php, partials/content-cover-metadata.php
Partial fix for pressbooks/pressbooks#2595
This PR adds support to the structural changes in the institutions field (see pressbooks/pressbooks#2602).
1. Add one or more institutions to the book in the Book Info option
1. Go to the book homepage and check if the information is displayed properly (when the book has no institutions, this won't be shown in the homepage)
=> feat: Support new institution structure

assets/src/scripts/routes/common.js
WCAG requires svgs used as images to be labeled in the same way as a standard images. Currently the up/down areas in the TOC area are not labeled for accessibility.
This commit will append the passed naming of the TOC - ie "Content" to also map to the up/down arrows aria labels which performs more consistently that alt or labeledby in this context.
=> Adding aria-label for arrows as required by WCAG

header.php
Fix for https://github.com/pressbooks/pressbooks-book/issues/998
To test:
1. Change the default logo for your network (`wp-admin/customize.php?return=%2Fwp%2Fwp-admin%2F`)
2. Visit the home page of a book and inspect the logo. Aria label should now be the title of your network, not the title of the book.
3. Change the Site Title for your network
4. Visit the home page of a book and inspect the logo. Aria label should now be the updated network Site Title.
=> Fix aria label for site logo

assets/book/typography/styles/_shapeshifter-font-stack-epub.scss, assets/book/typography/styles/_shapeshifter-font-stack-prince.scss, assets/book/typography/styles/_shapeshifter-font-stack-web.scss
Partial fix for https://github.com/pressbooks/pressbooks-book/issues/932. Requires https://github.com/pressbooks/pressbooks/pull/2798
To test:
1. Apply the McLuhan or Malala theme to your book
2. Go to theme options: and select Alegreya Sans as the header or body font for web, pdf, and epub exports
3. View the webbook and confirm that the font displayed is Alegreya Sans
4. Produce and EPUB and PDF exports and confirm that the fonts displayed are Alegreya Sans
=> fix Alegreya Sans font import

header.php
Use `https://pressbooks.com/adapt-open-textbooks?utm_source=book&utm_medium=banner&utm_campaign=bbc` as requested by @SevenSidedSquare
=> Update CTA link to use Google UTM tags

inc/actions/namespace.php
At present, users can apply 'custom styles' to alter the CSS of their webbook, EPUB and PDF exports. CSS that they enter through this feature is applied to every page inside of a book, but was NOT applied to the webbook home page itself. This is unexpected behaviour, since custom CSS is already applied to every page within the book's reading interface (front matter, chapters, etc), as well as the buy book page. This PR enqueues these custom styles on book homepages, so CSS changes appear on this page as well.
To test:
1. Apply custom web styles that target some element of the webbook home page. For example: 
```
.cta {
display: none;
}
.home .book-header__title {
color: pink;
}
```
2. Observe no change to the webbook homepage.
3. Check out this branch
4. Observe that the webbook homepage …
=> Allow custom styles to be applied to book home page

private.php
Fix for https://github.com/pressbooks/private/issues/1018
To test:
1. Set a book to private
2. Visit the book home page and sign in -- you should be redirected to the home page instead of the admin menu
3. Visit any 'show in web' content inside the book and sign in -- you should be redirected to the page you signed in from instead of the admin menu
=> Change redirect behaviour after signing in from private book content

.github/workflows/standards-and-tests.yml, README.md, composer.json, composer.lock, phpcs.ruleset.xml, style.css
This PR updates this repo to require PHP 8.0 and adds PHP 8.1 to the experimental test matrix. It also updates some dependencies. Partial fix for https://github.com/pressbooks/private/issues/1024.
=> Require PHP 8 and bump dependencies
